apiVersion: v1
kind: Service
metadata:
  name: coinbase-service
  labels:
    app: coinbase
spec:
  type: LoadBalancer
  selector:
    app: coinbase
    version: ${DEPLOYMENT_VERSION}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

